### Acest dataset reprezinta - Oferta (energia care poate fi produsa)

Solar Power Generation Data 

#### datele sunt luate de la o centrala fotovoltaica din India. 

sunt impartite din 2 csv:
1. generation data - cat curent se produce
2. senzorii pentru vreme - conditiile atmostferice in acele momente

In [2]:
import pandas as pd

# incarcare dataset
df_gener = pd.read_csv('CSVs/Plant_1_Generation_Data.csv')
df_sensor = pd.read_csv('CSVs/Plant_1_Weather_Sensor_Data.csv')

#### Tipurile de date - energia solara

In [3]:
df_gener.head()

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD
0,15-05-2020 00:00,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6259559.0
1,15-05-2020 00:00,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6183645.0
2,15-05-2020 00:00,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6987759.0
3,15-05-2020 00:00,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7602960.0
4,15-05-2020 00:00,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7158964.0

#### Semnificatie coloane:
- date_time - timpul in intervale de 15 min
- source_key - id-ul fiecarui panou solar
- dc_power - in kW - puterea bruta de intrare
- ac_power - in kW - puterea de iesire (variabila tinta)
- yield - energia solara cumulata

##### Despre bateriile de depoziteaza aceasta energie 
Pornind de aici trebuie vazut: 
- randamentul de incarcare/descarcare
- degradarea lor
-

In [5]:
df_gener.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68778 entries, 0 to 68777
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DATE_TIME    68778 non-null  object
 1   PLANT_ID     68778 non-null  int64
 2   SOURCE_KEY   68778 non-null  object
 3   DC_POWER     68778 non-null  float64
 4   AC_POWER     68778 non-null  float64
 5   DAILY_YIELD  68778 non-null  float64
 6   TOTAL_YIELD  68778 non-null  float64
dtypes: float64(4), int64(1), object(2)
memory usage: 3.7+ MB

#### Tipurile de date - adunate din senzorii pentru vreme

In [4]:
df_sensor.head()

,DATE_TIME,PLANT_ID,SOURCE_KEY,AMBIENT_TEMPERATURE,MODULE_TEMPERATURE,IRRADIATION
0,2020-05-15 00:00:00,4135001,HmiyD2TTLFNqkNe,25.184316,22.857507,0.0
1,2020-05-15 00:15:00,4135001,HmiyD2TTLFNqkNe,25.084589,22.761668,0.0
2,2020-05-15 00:30:00,4135001,HmiyD2TTLFNqkNe,24.935753,22.592306,0.0
3,2020-05-15 00:45:00,4135001,HmiyD2TTLFNqkNe,24.846130,22.360852,0.0
4,2020-05-15 01:00:00,4135001,HmiyD2TTLFNqkNe,24.621525,22.165423,0.0

### Semnificatie coloane:
- ambient_temp - temperatura aerului
- module_temperature - temperatura panourilor
- irradiation - radiatia solara (predictorul)

In [6]:
df_sensor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3182 entries, 0 to 3181
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   DATE_TIME            3182 non-null   object
 1   PLANT_ID             3182 non-null   int64
 2   SOURCE_KEY           3182 non-null   object
 3   AMBIENT_TEMPERATURE  3182 non-null   float64
 4   MODULE_TEMPERATURE   3182 non-null   float64
 5   IRRADIATION          3182 non-null   float64
dtypes: float64(3), int64(1), object(2)
memory usage: 149.3+ KB